---
title: "String"
author: "박찬영"
date: "2024-08-26"
output: 
   pdf_document:
    latex_engine: xelatex
header-includes:
- \usepackage[hangul]{kotex}
- \setmainhangulfont{나눔고딕}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

tidyverse와 stringr library를 사용합니다.
문자열을 다룰 때는 stringr이 좋다. (tidyverse에 없음)
```{r include=FALSE}
library(tidyverse)
library(stringr)
```


## 문자열 다루기


```{r string}
#문자열은 따옴표로 묶기가 기본
str1 = "This is a string"
str2 = '인용문이 있으면 "작은따옴표를 쓴다" 크크'
#따옴표 기호를 쓰고싶으면 \를 사용해라
str="따옴표 출력 하고 싶어요 \" 이렇게~"
"이거는 백슬래시 출력이에요 \\ 이렇게"
#근데 터미널에서 \도 잘보이는데요

str_view(str) #얘가 진짜 출력이에요~

r"(얘를 쓰면요~ \ " " ? 이딴거 다 돼요~)"

str_view("크크 \n \t 이런건 다 알죠?")


"\uc804\uc0b0\ud1b5\uacc4" #유니코드 출력법

length("문자열의 길이") #는 1이다 !

str_length("이게 ㄹㅇ 문자열 길이")

str_length(c("하","하하",NA))

str_c("x", "y") #기본 결합
str_c("x","y",sep="..") #구분자

str_c("나는",c("박찬영", "박찬빵"), "입니다.", sep=" ")
#이러면 벡터로 결합된다 굿굿


str_c(
  "Good ", "morning", " ", "chan",
  if (FALSE) " and HAPPY BIRTHDAY",
  "."
)

#if문 사용으로 문자열을 선택할 수 있음

str_c(c("나는", "나는","저팔계"), collapse = " ")
#collapse를 쓰면 문자열 벡터를 합칠 수 있다

#문자열을 슬라이싱 해보자

str_sub("Apple", 1,3) #1에서 3까지
str_sub(c("나는야","너는야","저팔계야"), 1,2)
str_sub(c("나는야","너는야","저팔계야"), -2,-1)
#음수 사용하면 뒤로간다

x <- c("Apple", "Banana", "Pear")
str_sub(x, 1, 1) <- str_to_lower(str_sub(x, 1, 1))
x
#부분 할당이 된다...
```
`
`

## 정규 표현식

정규표현식은 꽤 어렵다...
일단 매칭탐지부터 가자

```{r regexs}
x=c("apple","banana","pear")

str_detect(x, "e") #각 요소별로 e가 들어가는지 확인
#논리형 벡터 반환이라 filter에 잘 쓰인다

library(babynames)

babynames %>% filter(str_detect(name, "x"))

#논리 벡터이기 때문에 sum은 일치수 mean은 일치율을 알려준다

babynames %>% 
    group_by(year) %>%
    summarise(prop_x = mean(str_detect(name, "x"))) %>%
    ggplot(aes(year, prop_x)) +
    geom_line() +
    theme(aspect.ratio = 1/2)

#str_detect는 기본이 정확한 포함이지만 여러가지 용법이 있다

str_detect(c("a","ab","ea"), "a.")
#a. 은 a뒤에 뭔가가 오는 것을 의미한다 a를 포함이 아니다

str_detect(x, ".a.") #이러면 a앞뒤에 한 글자씩 있어야 함

str_view(x, ".a.") #얘는 시각적 피드백을 준다

str_view(x, "^a") #a로 시작하는 거 찾기
str_view(x, "a$") #a로 끝나는 거 찾기 
y <- c("apple pie", "apple", "apple cake", "pine apple")

str_view(y, "^apple$") #강제하기
str_view(y, "apple$")

str_view(c("a","ab","abb","abcc"),"abc?") #하면 c는 선택사항이 된다 ab는 필수
str_view(c("a","ab","abb","abbb"),"ab+") #하면 b를 더할 수 있다 ab는 필수
str_view(c("a","ab","abbb","abcabbb"),"ab*") #하면 b는 선택사항이고 반복가능 +와 ?의 합

names=c("Hadley","Mine","Garrett")

str_view(names, "[aeiou]") #[]는 안에 있는거를 다 찾음
str_view(names, "[^aeiou]") #[]안의 ^는 제외
str_view(names, "[a^eiou]") #이런건 안됨ㅋㅋㅋ
#핵심은 각각 찾아준다는 것
str_view(names, "[^aeiou]+") #+랑 합치면 이렇게됨
#연결해서 찾아줌 (반복 허용이라)

str_view(x,"p{2}") #{n} 은 갯수
str_view(x, "p{1,2}") #{n,m} 은 n이상 m이하
str_view(x, "p{1,}") #1, 하면 이상
str_view(x, "p{1,2}?") #뭔 작동이여
str_view(x,"a[pr]+?") #이런 거?도 몰루

str_view(x,"(..)\\1") #\n 은 정규표현식인데 문자열이라서 \\n으로 써야하고 앞의 그룹표현식에대한 참조임
str_view(x,"(a.)\\1")

head(words) #이런 벡터가 이미 존재


df = tibble(word=words, i=seq_along(words))
head(df)

df %>% filter(str_detect(word, "x$")) #x로 끝나는 단어 세기


str_count(words,"a") #a가 들어간 수 카운트
str_count("abababa","aba") #카운트는 겹치지않음
mean(str_count(words,"[aeiou]")) #모음포함율

str_replace(x, "[aeiou]","-") #교체 근데 하나만 교체됨

str_replace_all(x, "[aeiou]","-") #이러면 다 교체



```

`
`
## 문자열 추출

```{r exmatch}
head(sentences) #720개의 문장열이다

colpat=str_c(c("red","orange","yellow","green","blue","purple"),collapse = "|")
colpat

colsen=str_subset(sentences,colpat) #str_subset은 정규표현식 패턴에 맞는 요소만 남긴다
match=str_extract(colsen,colpat)
match #각 요소에서 패턴에 맞는 문자열을 빼오기

more = colsen[str_count(colsen, colpat)>1] #응용 색 두개이상만 찾기

more %>% str_extract(colpat)
#보면 알겠지만 str_extract는 한 요소에서 처음 찾은거만 리턴한다
more %>% str_extract_all(colpat) #임마는 2차원 리스트로 싹 찾아준다

more %>% str_extract_all(colpat, simplify = TRUE) #행렬로 해줌 "간단히"

noun="(a|the) ([^ ]+)" #a the 뒤에 띄어쓰기하고 공백 아닌놈 오는걸로 패턴만듬
has_noun=sentences %>% str_subset(noun) %>% head(10)

has_noun

has_noun %>% str_extract(noun)
has_noun %>% str_match(noun) #요소 각 그룹


#tidyr의 extract는 티블에서 작동합니다

tibble(sentence = sentences) %>% extract(sentence, c("article", "noun"), noun, remove = FALSE)
#결과보면 어떤 원리인지 이해됨, 추출열, 새로운열 이름, 패턴, 기존 데이터없앨지 말지


sentences %>% 
  str_replace("([^ ]+) ([^ ]+) ([^ ]+)", "\\1 \\3 \\2") %>% 
  head(5)
#2번째와 3번째의 표현식의 참조를 통해 자리를 바꿈

```

`
`
## 문자열 쪼개기

```{r split}
sentences %>% head(5) %>% str_split(" ") #공백기준 스플릿 당연히 정규표현식 가능
sentences %>% head(5) %>% str_split(" ", simplify = TRUE) #행렬로 간단히

dic=c("Name : Hadley", "Country : NZ", "Age : 35") #파이썬의 딕셔너리같은 느낌
dic %>% str_split(" : ", simplify = TRUE, n=2) #이러면 행렬로 변환가능

boundary("word") #복잡하네요

sen <- "This is a sentence.  This is another sentence."
str_view_all(sen, boundary("word")) #이런거 가능

str_split(sen, " ")

str_split(sen, boundary("word")) #이런것도 가능
```