---
title: "데이터 변환"
author: "박찬영"
date: "2024-08-21"
output: 
   pdf_document:
    latex_engine: xelatex
header-includes:
- \usepackage[hangul]{kotex}
- \setmainhangulfont{나눔고딕}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

tidyverse와 nycflights13 library를 사용합니다.

```{r include=FALSE}
library(tidyverse)
library(nycflights13)
```

```{r fligths}
fl=flights
head(fl)
```

`
`
## 데이터 필터링
```{r filter}
filter(fl, month==1, day==1) #1월 1일 데이터만 남기기

x=c(NA, 1, NA) #NA는 결측치입니다.
is.na(x) #결측치를 확인하는 함수

df = tibble(x=c(1, NA, 3))
filter(df, x>1)
filter(df, is.na(x) | x>1) #is.na 사용법

```
어찌보면 filter 함수는 bool 벡터값을 이용하는 것 같다.

`
`
다음은 데이터 정렬이다
```{r arr}
arrange(fl, year, month, day) #우선순위 따라 기본은 오름차순
tmp= arrange(fl, desc(arr_delay)) #내림차순 하는법

arrange(df, x) #결측치는 항상 마지막

```
`
`
열을 골라보자
```{r sel}
select(fl, dep_delay, arr_delay) #원하는 열을 고르기
select(fl, dep_time:arr_delay) #주루룩 고르기는 : 사용
select(fl, -(dep_time)) # - 달면 걔 빼고
select(fl, c(1,3,4,5)) #벡터로 직관적으로 구할 수 있음.
select(fl, time_hour, everything()) #순서 체인지 같은것도 가능

fl_sml = select(fl, year:day, ends_with("delay"), distance, air_time) #응용

rename(fl, dt=dep_time) #이름바꾸기 A로 B를 바꾼다의 문법
```
`
`
데이터의 추가
```{r add}
mutate(fl_sml, gain=arr_delay - dep_delay, speed = distance/air_time*60)
mutate(fl_sml, gain=arr_delay - dep_delay, hours=air_time/60, gain_per_hour = gain/hours) #방금 만든거를 참조가능
transmute(fl_sml, gain=arr_delay - dep_delay, hours=air_time/60, gain_per_hour = gain/hours) #새거만 남기기
```

## 데이터 요약

```{r sm}
summarise(fl, delay=mean(dep_delay, na.rm=TRUE), maxd=max(dep_delay, na.rm=TRUE), mind=min(dep_delay, na.rm=TRUE)) #출력값이 데이터프레임임

#group_by는 같은 값끼리 데이터프레임열을 만들어주는데 같이 쓰기 좋음

a=fl %>%
group_by(year, month, day) %>% #연 월 일 별로 다 데이터프레임을 쪼갬, 순서가 중요함
summarise(delay=mean(dep_delay, na.rm=TRUE)) #각 데이터프레임에서 평균을 냄


not_cancelled <- fl %>% filter(!is.na(dep_delay), !is.na(arr_delay))
not_cancelled %>% 
      group_by(year, month, day) %>% 
      summarise(
        first_dep = min(dep_time), 
        last_dep = max(dep_time)
      ) #예제


not_cancelled %>% group_by(year, month, day) %>%
    summarise(hour_perc=length(arr_delay[arr_delay >60])/length(arr_delay)) #개못함 

not_cancelled %>% group_by(year, month, day) %>%
    summarise(hour_perc=mean(arr_delay>60)) #개천재 벡터와 부울 변수를 존나 잘씀

fl_sml %>% 
      group_by(year, month, day) %>%
      filter(rank(desc(arr_delay)) < 10) #이런것도 가능 그룹바이 굿굿


pop = not_cancelled %>% group_by(dest) %>% filter(n()>10000)

summer= pop %>% ungroup() %>%
    select(year:day, dep_time, sched_dep_time, dep_delay, dest) %>%
    filter(month<9, month>5, dep_time>=900, dep_time<=1500)

rs=summer %>% group_by(dest, year, month, day) %>%
    arrange(dep_delay) %>%
    summarise(min_delay = first(dep_delay), rec_time=first(sched_dep_time%/%100))

rs %>% group_by(dest, rec_time) %>% summarise(m=mean(min_delay), sd= sd(min_delay), 
                                low=m-2*sd, high=m+2*sd ) %>%
ggplot(aes(x=rec_time, y=m, ymin=low, ymax=high)) +
    geom_pointrange() +
    theme(aspect.ratio = 1/2) +
    facet_wrap(~dest, nrow=2)

rs %>% group_by(dest, rec_time) %>% summarise(mean_delay=mean(min_delay)) %>% 
    arrange(mean_delay) %>% summarise(rec_timee=first(rec_time), mean_delay=first(mean_delay))

#오늘의 결론 summarise() 돼서 짜바리된 그룹은 사라진다. 즉 1개짜리 그룹은 그룹 취급을 안받는다.
```